apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: rewrite
  namespace: default
spec:
  rules:
  - host: nugi.local
    http:
      paths:
      - backend:
          serviceName: wordpress-server
          servicePort: 80
        path: /
